name: DuelMe
version: 0.8.1
author: teozfrank
main: com.teozcommunity.teozfrank.duelme.main.DuelMe
commands:
    duel:
        description: Access to duel commands
        permission: duelme.player.info
        permission-message: You do not have permission for this command!
        usage: /<command>
    dueladmin:
        description: Access to dueladmin commands
        permission: duelme.admin.info
        permission-message: You do not have permission for this command!
        useage: /<command>
permissions:
    duelme.*:
        description: Gives access to all toolkit permissions
        children:
            duelme.player.*: true
            duelme.admin.*: true
    duelme.admin.*:
        description: Gives access to all toolkit staff commands
        children:
            duelme.admin.info: true
            duelme.admin.create: true
            duelme.admin.set: true
            duelme.admin.remove: true
            duelme.admin.list: true
            duelme.admin.update.notify: true
            duelme.admin.reload: true
    duelme.player.*:
        description: Gives access to all player commands
        children:
            duelme.player.info: true		
            duelme.player.accept: true
            duelme.player.send: true
            duelme.player.leave: true
            duelme.player.list: true
    duelme.player.info:
        description: allows a player to read the info about the duel command
        default: op
    duelme.player.accept:
        description: allows a player to accept a duel request
        default: op
    duelme.player.send:
        description: allows a player to send a duel request
        default: op
    duelme.player.leave:
        description: allows a player to leave a duel
        default: op
    duelme.player.list:
        description: allows a player to list the duels and there status
        default: op
    duelme.admin.info:
        description: allows an admin to see the information about the dueladmin command
        default: op
    duelme.admin.create:
        description: allows an admin to create a duel arena
        default: op
    duelme.admin.set:
        description: allows an admin to set the lobby spawn
        default: op
    duelme.admin.remove:
        description: allows an admin to remove a duel arena
        default: op
    duelme.admin.list:
        description: allows an admin to list all the duel arenas
        default: op
    duelme.admin.update.notify:
        description: notifys admins of plugin updates
        default: op
    duelme.admin.reload:
        description: reloads the plugin configs from disk
        default: op